# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-07-23 04:43
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fack', '0004_auto_20181116_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionscore',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
